/* ═══════════════════════════════════════════════════════════
   WINNER — backend/config/metadata.js (Google Merchant Metadata)
   ═══════════════════════════════════════════════════════════ */
"use strict";

const PRODUCT_METADATA = {
  P001: {
    googleCategory:
      "Apparel & Accessories > Clothing > Outerwear > Hoodies & Sweatshirts",
    productType: "Streetwear > Crop Hoodie Oversize",
    mpn: "WIN-P001",
    gtin: "7700000000012",
    gender: "female",
    ageGroup: "adult",
    color: "Negro grafito",
    size: "XS,S,M,L,XL,XXL",
    material: "Algodón peinado 320g",
    pattern: "Liso",
    shippingWeight: "0.65 kg",
    customLabel0: "Oferta",
    customLabel1: "Hoodies",
    additionalImages: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900&q=80",
    ],
  },
  P002: {
    googleCategory: "Apparel & Accessories > Clothing > Dresses",
    productType: "Streetwear > Mini Dress Urbana",
    mpn: "WIN-P002",
    gtin: "7700000000013",
    gender: "female",
    ageGroup: "adult",
    color: "Blanco hueso",
    size: "XS,S,M,L,XL,XXL",
    material: "Satín stretch",
    pattern: "Texturizado",
    shippingWeight: "0.52 kg",
    customLabel0: "Novedad",
    customLabel1: "Vestidos",
    additionalImages: [
      "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=900&q=80",
    ],
  },
  P003: {
    googleCategory: "Apparel & Accessories > Clothing > Activewear",
    productType: "Streetwear > Set Legging + Top",
    mpn: "WIN-P003",
    gtin: "7700000000014",
    gender: "female",
    ageGroup: "adult",
    color: "Negro/lima",
    size: "XS,S,M,L,XL",
    material: "Licra compresiva 4-way",
    pattern: "Bicolor",
    shippingWeight: "0.70 kg",
    customLabel0: "Oferta",
    customLabel1: "Conjuntos",
    additionalImages: [],
  },
  P004: {
    googleCategory: "Apparel & Accessories > Clothing > Outerwear > Blazers",
    productType: "Streetwear > Blazer Crop",
    mpn: "WIN-P004",
    gtin: "7700000000015",
    gender: "female",
    ageGroup: "adult",
    color: "Beige arena",
    size: "XS,S,M,L,XL",
    material: "Lino stretch",
    pattern: "Liso",
    shippingWeight: "0.60 kg",
    customLabel0: "Premium",
    customLabel1: "Blazers",
    additionalImages: [],
  },
  P005: {
    googleCategory: "Apparel & Accessories > Clothing > Pants",
    productType: "Streetwear > Jogger Mom Fit",
    mpn: "WIN-P005",
    gtin: "7700000000016",
    gender: "female",
    ageGroup: "adult",
    color: "Gris jaspeado",
    size: "XS,S,M,L,XL,XXL",
    material: "French terry",
    pattern: "Liso",
    shippingWeight: "0.55 kg",
    customLabel0: "Básicos",
    customLabel1: "Joggers",
    additionalImages: [],
  },
  P006: {
    googleCategory:
      "Apparel & Accessories > Clothing > Shirts & Tops > T-shirts",
    productType: "Streetwear > Camiseta Ribbed",
    mpn: "WIN-P006",
    gtin: "7700000000017",
    gender: "female",
    ageGroup: "adult",
    color: "Crema",
    size: "XS,S,M,L,XL,XXL",
    material: "Algodón acanalado",
    pattern: "Acanalado",
    shippingWeight: "0.35 kg",
    customLabel0: "Oferta",
    customLabel1: "Tops",
    additionalImages: [],
  },
  P007: {
    googleCategory: "Apparel & Accessories > Clothing > Pants",
    productType: "Streetwear > Shorts Cargo Y2K",
    mpn: "WIN-P007",
    gtin: "7700000000018",
    gender: "female",
    ageGroup: "adult",
    color: "Caqui",
    size: "XS,S,M,L,XL",
    material: "Gabardina",
    pattern: "Cargo",
    shippingWeight: "0.42 kg",
    customLabel0: "Oferta",
    customLabel1: "Shorts",
    additionalImages: [],
  },
  P008: {
    googleCategory: "Apparel & Accessories > Clothing > Dresses",
    productType: "Streetwear > Vestido Asimétrico",
    mpn: "WIN-P008",
    gtin: "7700000000019",
    gender: "female",
    ageGroup: "adult",
    color: "Negro",
    size: "XS,S,M,L,XL",
    material: "Satín mate",
    pattern: "Liso",
    shippingWeight: "0.50 kg",
    customLabel0: "Premium",
    customLabel1: "Vestidos",
    additionalImages: [],
  },
  P009: {
    googleCategory:
      "Apparel & Accessories > Clothing > Shirts & Tops > T-shirts",
    productType: "Streetwear > Oversize Tee W Logo",
    mpn: "WIN-P009",
    gtin: "7700000000020",
    gender: "male",
    ageGroup: "adult",
    color: "Blanco puro",
    size: "XS,S,M,L,XL,XXL",
    material: "Algodón orgánico 200g",
    pattern: "Grafiti",
    shippingWeight: "0.35 kg",
    customLabel0: "Básicos",
    customLabel1: "Camisetas",
    additionalImages: [
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=900&q=80",
    ],
  },
  P010: {
    googleCategory: "Apparel & Accessories > Clothing > Pants",
    productType: "Streetwear > Jogger Cargo Premium",
    mpn: "WIN-P010",
    gtin: "7700000000021",
    gender: "male",
    ageGroup: "adult",
    color: "Caqui militar",
    size: "S,M,L,XL,XXL",
    material: "Gabardina stretch",
    pattern: "Cargo",
    shippingWeight: "0.58 kg",
    customLabel0: "Oferta",
    customLabel1: "Joggers",
    additionalImages: [],
  },
  P011: {
    googleCategory: "Apparel & Accessories > Clothing > Outerwear > Jackets",
    productType: "Streetwear > Bomber Reflex Táctico",
    mpn: "WIN-P011",
    gtin: "7700000000022",
    gender: "male",
    ageGroup: "adult",
    color: "Negro metálico",
    size: "S,M,L,XL",
    material: "Nylon técnico reflectivo",
    pattern: "Reflectivo",
    shippingWeight: "0.72 kg",
    customLabel0: "Novedad",
    customLabel1: "Bomber",
    additionalImages: [],
  },
  P012: {
    googleCategory:
      "Apparel & Accessories > Clothing > Outerwear > Hoodies & Sweatshirts",
    productType: "Streetwear > Hoodie Canguro",
    mpn: "WIN-P012",
    gtin: "7700000000023",
    gender: "male",
    ageGroup: "adult",
    color: "Gris carbón",
    size: "XS,S,M,L,XL,XXL",
    material: "Fleece pesado 380g",
    pattern: "Liso",
    shippingWeight: "0.68 kg",
    customLabel0: "Básicos",
    customLabel1: "Hoodies",
    additionalImages: [],
  },
  P013: {
    googleCategory: "Apparel & Accessories > Clothing > Activewear",
    productType: "Streetwear > Camiseta Dry-Fit",
    mpn: "WIN-P013",
    gtin: "7700000000024",
    gender: "male",
    ageGroup: "adult",
    color: "Negro",
    size: "S,M,L,XL,XXL",
    material: "Poliéster técnico",
    pattern: "Liso",
    shippingWeight: "0.28 kg",
    customLabel0: "Sport",
    customLabel1: "Camisetas",
    additionalImages: [],
  },
  P014: {
    googleCategory: "Apparel & Accessories > Clothing > Pants",
    productType: 'Streetwear > Short Deportivo 5"',
    mpn: "WIN-P014",
    gtin: "7700000000025",
    gender: "male",
    ageGroup: "adult",
    color: "Negro",
    size: "S,M,L,XL,XXL",
    material: "Poliéster stretch",
    pattern: "Liso",
    shippingWeight: "0.30 kg",
    customLabel0: "Oferta",
    customLabel1: "Shorts",
    additionalImages: [],
  },
  P015: {
    googleCategory: "Apparel & Accessories > Clothing > Outerwear > Jackets",
    productType: "Streetwear > Chaqueta Rompevientos Neon",
    mpn: "WIN-P015",
    gtin: "7700000000026",
    gender: "male",
    ageGroup: "adult",
    color: "Lima neon",
    size: "S,M,L,XL,XXL",
    material: "Nylon ligero",
    pattern: "Liso",
    shippingWeight: "0.55 kg",
    customLabel0: "Oferta",
    customLabel1: "Chaquetas",
    additionalImages: [],
  },
  P016: {
    googleCategory: "Apparel & Accessories > Clothing > Pants",
    productType: "Streetwear > Pantalón Cargo Multicorreas",
    mpn: "WIN-P016",
    gtin: "7700000000027",
    gender: "male",
    ageGroup: "adult",
    color: "Negro",
    size: "S,M,L,XL,XXL",
    material: "Gabardina técnica",
    pattern: "Multicorreas",
    shippingWeight: "0.70 kg",
    customLabel0: "Premium",
    customLabel1: "Cargo",
    additionalImages: [],
  },
  P017: {
    googleCategory: "Apparel & Accessories > Clothing Accessories > Hats",
    productType: "Streetwear > Bucket Hat Logo W",
    mpn: "WIN-P017",
    gtin: "7700000000028",
    gender: "unisex",
    ageGroup: "adult",
    color: "Beige arena",
    size: "U",
    material: "Lona liviana",
    pattern: "Liso",
    shippingWeight: "0.20 kg",
    customLabel0: "Accesorios",
    customLabel1: "Sombreros",
    additionalImages: [],
  },
  P018: {
    googleCategory: "Apparel & Accessories > Clothing Accessories > Hats",
    productType: "Streetwear > Gorra Snapback Premium",
    mpn: "WIN-P018",
    gtin: "7700000000029",
    gender: "unisex",
    ageGroup: "adult",
    color: "Negro",
    size: "U",
    material: "Lona rígida",
    pattern: "Liso",
    shippingWeight: "0.22 kg",
    customLabel0: "Básicos",
    customLabel1: "Gorras",
    additionalImages: [],
  },
  P019: {
    googleCategory: "Apparel & Accessories > Bags > Backpacks",
    productType: "Streetwear > Mochila Táctica Urbana",
    mpn: "WIN-P019",
    gtin: "7700000000030",
    gender: "unisex",
    ageGroup: "adult",
    color: "Negro carbón",
    size: "U",
    material: "Poliéster 600D",
    pattern: "Geométrico",
    shippingWeight: "0.95 kg",
    customLabel0: "Oferta",
    customLabel1: "Mochilas",
    additionalImages: [],
  },
  P020: {
    googleCategory: "Apparel & Accessories > Handbags > Crossbody Bags",
    productType: "Streetwear > Bolso Crossbody Cuero PU",
    mpn: "WIN-P020",
    gtin: "7700000000031",
    gender: "female",
    ageGroup: "adult",
    color: "Marrón",
    size: "U",
    material: "Cuero sintético PU",
    pattern: "Liso",
    shippingWeight: "0.65 kg",
    customLabel0: "Oferta",
    customLabel1: "Bolsos",
    additionalImages: [],
  },
  P021: {
    googleCategory: "Apparel & Accessories > Jewelry > Necklaces",
    productType: "Streetwear > Cadena Cubana Acero",
    mpn: "WIN-P021",
    gtin: "7700000000032",
    gender: "unisex",
    ageGroup: "adult",
    color: "Plateado",
    size: "U",
    material: "Acero inoxidable 316L",
    pattern: "Cubano",
    shippingWeight: "0.15 kg",
    customLabel0: "Oferta",
    customLabel1: "Joyería",
    additionalImages: [],
  },
  P022: {
    googleCategory:
      "Apparel & Accessories > Clothing Accessories > Sunglasses & Eyewear",
    productType: "Streetwear > Gafas Espejadas Y2K",
    mpn: "WIN-P022",
    gtin: "7700000000033",
    gender: "unisex",
    ageGroup: "adult",
    color: "Espejado multicolor",
    size: "U",
    material: "TR90 + policarbonato",
    pattern: "Espejado",
    shippingWeight: "0.08 kg",
    customLabel0: "Oferta",
    customLabel1: "Gafas",
    additionalImages: [],
  },
  P023: {
    googleCategory: "Apparel & Accessories > Bags > Waist Packs",
    productType: "Streetwear > Riñonera Neon Reflectiva",
    mpn: "WIN-P023",
    gtin: "7700000000034",
    gender: "unisex",
    ageGroup: "adult",
    color: "Lima reflectivo",
    size: "U",
    material: "Nylon técnico",
    pattern: "Reflectivo",
    shippingWeight: "0.25 kg",
    customLabel0: "Novedad",
    customLabel1: "Riñoneras",
    additionalImages: [],
  },
  P024: {
    googleCategory: "Apparel & Accessories > Clothing > Socks",
    productType: "Streetwear > Set Medias Deportivas x3",
    mpn: "WIN-P024",
    gtin: "7700000000035",
    gender: "unisex",
    ageGroup: "adult",
    color: "Blanco/negro/gris",
    size: "U",
    material: "Algodón + elastano",
    pattern: "Logos",
    shippingWeight: "0.12 kg",
    customLabel0: "Básicos",
    customLabel1: "Medias",
    additionalImages: [],
  },
  P025: {
    googleCategory:
      "Apparel & Accessories > Clothing Accessories > Scarves & Wraps",
    productType: "Streetwear > Bufanda Tubular Streetwear",
    mpn: "WIN-P025",
    gtin: "7700000000036",
    gender: "unisex",
    ageGroup: "adult",
    color: "Negro",
    size: "U",
    material: "Microfibra técnica",
    pattern: "Liso",
    shippingWeight: "0.10 kg",
    customLabel0: "Básicos",
    customLabel1: "Accesorios",
    additionalImages: [],
  },
};

const MERCHANT_SALE_DATE =
  "2026-01-01T00:00:00-05:00/2026-12-31T23:59:59-05:00";
const DEFAULT_SHIPPING = "CO::0.00 COP";
const DEFAULT_TAX = "CO::0.00 COP";

module.exports = {
  PRODUCT_METADATA,
  MERCHANT_SALE_DATE,
  DEFAULT_SHIPPING,
  DEFAULT_TAX,
};
